spring.application.name=Final
spring.data.mongodb.uri=mongodb://localhost:27017/transitdb
spring.data.mongodb.database=transitdb
spring.datasource.url=jdbc:postgresql://localhost:5432/transitdb
spring.datasource.username=postgres
spring.datasource.password=7Monster7
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
